### ISSUE TITLE
Do something when the user clicks on the icon on the toolbar

### ISSUE THREAD

**Issue by yogodoshi** [anthonysousa/trellodoro#2]
Now it isn't doing anything. It may seem its broken. Maybe show a tutorial?

**Comment by anthonysousa** [comment]
I was thinking about open the settings page: https://github.com/anthonysousa/trellodoro/commit/90847ed115bc8e5b2652d65277198a04b64bf3f8

What do you think?

**Comment by yogodoshi** [comment]
Even better :+1:
