### ISSUE TITLE
Ask for permission to enable notifications earlier

### ISSUE THREAD

**Issue by yogodoshi** [anthonysousa/trellodoro#6]
When I used it for the first time, I didn't receive the notification that my pomodoro ended but I hadn't enabled the notifications for trello.com yet, so instead of notifying me, it just asked me to enable the notifications.

**Comment by anthonysousa** [comment]
Fixed! https://github.com/anthonysousa/trellodoro/commit/8269a783322f948df6187d07e55d4e18167cc1fb
